// functions/helpers/lang.js
// Bilingual messages (Myanmar + English)

export const messages = {
    en: {
        welcome: "Hello! 👋\n\nSend your Facebook data export ZIP file to check who doesn't follow you back.\n\n📌 Commands:\n/help  — How to use\n/stats — Result summary\n/check — Not-following-back list\n/top10 — Latest 10 people\n/export — Full list (.txt + .csv)\n/lang  — Change language",
        help: "📖 How to Use\n════════════════════════════════════════\n\nUpload your Facebook \"Download Your Information\" ZIP file directly here.\n\nRequired files inside ZIP:\n• people_who_followed_you.json\n• who_you've_followed.json\n\nLimits:\n• Max file size: 20MB\n• Max 3 uploads per day\n\n/lang — Switch to Myanmar",
        gate: "🔒 This bot is exclusive to @illumoria_1 channel members.\n\nJoin the channel then tap the button below.",
        join_btn: "📢 Join @illumoria_1 Channel",
        recheck_btn: "✅ I've Joined — Verify Now",
        recheck_ok: "✅ Membership verified!\n\nYou can now upload your Facebook ZIP file.",
        recheck_fail: "❌ You're not a member yet. Join first, then tap again.",
        processing: "⏳ Processing your file…",
        invalid_zip: "❌ The file you sent is not a valid ZIP.",
        too_big: "❌ File exceeds 20MB limit.",
        json_miss: "❌ Required JSON files not found in ZIP.",
        proc_err: "❌ An error occurred while processing.",
        rate_limit: "⚠️ You can only upload 3 times per day.\nPlease try again tomorrow.",
        no_cache: "⚠️ Please upload your Facebook ZIP file first.\n(Results are cached for 2 hours)",
        all_follow: "🎉 Everyone you follow also follows you back!",
        lang_changed: "✅ Language changed to English.",
        lang_btn: "🌐 မြန်မာ သို့ ပြောင်းရန်",
        export_cap: "📄 Not-following-back full list",
        csv_cap: "📊 CSV file (open in Excel/Sheets)",
        card_cap: "📊 Facebook Analysis Summary Card",
        card_generating: "⏳ Generating summary card...",
        not_back_hdr: "❌ Not Following Back",
        top10_hdr: "🔟 Latest 10 People Not Following Back",
        followed_on: "Followed on",
        page_label: "Page",
        prev: "⬅️ Prev",
        next: "Next ➡️",
        stats_text: "📊 Facebook Analysis Result\n════════════════════════════════════════\n\n👥 Followers Count:    {followers}\n➡️ Following Count:    {following}\n🤝 Mutual Follow:      {mutual}\n❌ Not Following Back: {not_back}\n\n════════════════════════════════════════\n\n/check — Not Following Back list\n/top10 — Latest 10\n/export — .txt + .csv",
        admin_panel: "🛡️ Admin Panel\n════════════════════════════════════════\n\n👤 Total Users:        {users}\n📤 Total Uploads:      {uploads}\n📅 Today's Uploads:    {today}\n💾 Active Cache:       KV-based\n\n⏱️ Cache TTL:          2 hours",
        invalid_command: "Use /help to see available commands."
    },
    mm: {
        welcome: "မင်္ဂလာပါ! 👋\n\nFacebook followers/following data စစ်ဆေးဖို့\nFacebook ZIP ဖိုင်ကို ဤနေရာတွင် ပေးပို့ပါ။\n\n📌 Commands:\n/help  — အသုံးပြုနည်း\n/stats — ရလဒ် summary\n/check — follow ပြန်မလုပ်သူ စာရင်း\n/top10 — အသစ်ဆုံး 10 ဦး\n/export — full list (.txt + .csv)\n/lang  — ဘာသာ ပြောင်းရန်",
        help: "📖 Bot အသုံးပြုနည်း\n════════════════════════════════════════\n\nFacebook ၏ \"Download Your Information\" မှ download လုပ်ထားသော ZIP ဖိုင်ကို ဤ bot သို့ တိုက်ရိုက် upload လုပ်ပါ။\n\nZIP ထဲတွင် ပါဝင်ရမည့် ဖိုင်:\n• people_who_followed_you.json\n• who_you've_followed.json\n\nကန့်သတ်ချက်:\n• ဖိုင် အများဆုံး 20MB\n• တစ်ရက် upload 3 ကြိမ်\n\n/lang — မြန်မာ / English ပြောင်းရန်",
        gate: "🔒 ဤ bot ကို @illumoria_1 channel member များသာ အသုံးပြုနိုင်ပါသည်။\n\nChannel join ပြီးပါက အောက်ပါ ခလုတ်ကို နှိပ်ပါ။",
        join_btn: "📢 @illumoria_1 Channel Join ရန်",
        recheck_btn: "✅ Join ပြီးပါပြီ — စစ်ဆေးမည်",
        recheck_ok: "✅ Channel member အဖြစ် အတည်ပြုပြီးပါပြီ!\n\nFacebook ZIP ဖိုင်ကို ယခု ပေးပို့နိုင်ပါပြီ။",
        recheck_fail: "❌ Channel member မဟုတ်သေးပါ။ Join ပြီးမှ ထပ်နှိပ်ပါ။",
        processing: "⏳ စစ်ဆေးနေပါသည်…",
        invalid_zip: "❌ မှန်ကန်သော ZIP ဖိုင် မဟုတ်ပါ။",
        too_big: "❌ ဖိုင် 20MB ကျော်သောကြောင့် လက်မခံနိုင်ပါ။",
        json_miss: "❌ လိုအပ်သော JSON ဖိုင်များ မတွေ့ပါ။",
        proc_err: "❌ ဒေတာ စစ်ဆေးရာတွင် အမှားအယွင်း ရှိပါသည်။",
        rate_limit: "⚠️ တစ်ရက်တွင် 3 ကြိမ်သာ upload ပြုလုပ်နိုင်ပါသည်။\nမနက်ဖြန် ထပ်မံ ကြိုးစားပါ။",
        no_cache: "⚠️ ဦးစွာ Facebook ZIP ဖိုင်ကို upload လုပ်ပါ။\n(ရလဒ် 2 နာရီ သာ သိမ်းဆည်းပါသည်)",
        all_follow: "🎉 သင် follow လုပ်ထားသူ အားလုံး သင့်ကို ပြန် follow လုပ်ထားပါသည်!",
        lang_changed: "✅ ဘာသာ မြန်မာ သို့ ပြောင်းပြီးပါပြီ။",
        lang_btn: "🌐 English သို့ ပြောင်းရန်",
        export_cap: "📄 Follow ပြန်မလုပ်သူ full list",
        csv_cap: "📊 CSV ဖိုင် (Excel/Sheets တွင် ဖွင့်နိုင်)",
        card_cap: "📊 Facebook Analysis Summary Card",
        card_generating: "⏳ Summary card ထုတ်လုပ်နေပါသည်...",
        not_back_hdr: "❌ Not Following Back",
        top10_hdr: "🔟 လတ်တလော Follow လုပ်ထားသော်လည်း\n   Follow ပြန်မလုပ်သူ Top 10",
        followed_on: "Followed on",
        page_label: "စာမျက်နှာ",
        prev: "⬅️ နောက်",
        next: "ရှေ့ ➡️",
        stats_text: "📊 Facebook Analysis Result\n════════════════════════════════════════\n\n👥 Followers Count:    {followers}\n➡️ Following Count:    {following}\n🤝 Mutual Follow:      {mutual}\n❌ Not Following Back: {not_back}\n\n════════════════════════════════════════\n\n/check — Not Following Back list\n/top10 — အသစ်ဆုံး 10 ဦး\n/export — .txt + .csv",
        admin_panel: "🛡️ Admin Panel\n════════════════════════════════════════\n\n👤 Total Users:        {users}\n📤 Total Uploads:      {uploads}\n📅 Today's Uploads:    {today}\n💾 Active Cache:       KV-based\n\n⏱️ Cache TTL:          2 hours",
        invalid_command: "/help ကို အသုံးပြုပြီး commands များကို ကြည့်ပါ။"
    }
};
